apiVersion: aiops.ibm.com/v1alpha1
kind: IAConfig
metadata:
  name: ibm-ia-installer
  namespace: {{ .Values.namespace }}
spec:
  imagePullSecret: {{ .Values.imagePullSecret }}
  infraAutoComposableComponents:
    - enabled: true
      name: ibm-management-im-install
      spec: {}
    - enabled: true
      name: ibm-management-cam-install
      spec: {}
  license:
    accept: true
  storageClass: {{ .Values.storageClass }}