apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-infrastructure-automation-operator
  namespace: {{ .Values.namespace }}
spec:
  channel: {{ .Values.subscription_channel }}
  installPlanApproval: Automatic
  name: ibm-infrastructure-automation-operator
  source: {{ .Values.catalog_source }}
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.subscription_startingCSV }}